# Site settings
title: Francesco Rentocchini
#general_email: elizabethmcd93@gmail.com
#academic_email: eamcdani@mail.ubc.ca

#description: > # this means to ignore newlines until "baseurl:"
#  Microbial Ecology, Biotechnology, Multi-Omics
#baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://frarent/frarent.github.io" # the base hostname & protocol for your site

#github_username: elizabethmcd
#twitter_username: lizilla93
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title